version: '3.8'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'     # HTTP
      - '443:443'   # HTTPS
      - '81:81'     # Admin Panel
    volumes:
      - ./nginx-data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - genixo-network

  postgres:
    container_name: postgres-db
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=genixo
      - POSTGRES_PASSWORD=genixo
    ports:
      - '5432:5432'
    volumes:
      - /root/db_files:/var/lib/postgresql/data
    networks:
      - genixo-network

  genixo-server:
    container_name: search-parent
    image: ctekkaya/search:1.0
    restart: always
    networks:
      - genixo-network
    expose:
      - "8080"
    volumes:
      - /root/uploads:/app/uploads/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G


  genixo-app:
    container_name: search-web
    image: ctekkaya/search-web:1.0
    restart: always
    networks:
      - genixo-network
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  pgadmin_data:

networks:
  genixo-network:
    name: genixo-network
